### ISSUE TITLE
:export for consumption of variables in JavaScript

### ISSUE THREAD

**Issue by svdoever** [elycruz/rollup-plugin-sass#71] opened 2020-06-04 21:39 UTC
I try to use the :export construct as described in https://stackoverflow.com/questions/61517117/cannot-export-sass-variables-into-javascript?noredirect=1&lq=1 to be able to use values of SASS variables in my JavaScript but can't get it working:

```sass
@import "variables";

:export {

    // Export the color palette to make it accessible to JS
    some-light-blue: $some-light-blue;
    battleship-grey: $battleship-grey;
    // etc...

}
```

Should this work with rollup-plugin-sass, or is there another method to accomplish this?

**Comment by gloverab** [comment] 2020-12-17 23:27
Struggling with this exact same issue. Did you ever get it resolved?

**Comment by RossComputerGuy** [comment] 2022-08-14 22:53
I'm also looking to see this work.

**Comment by elycruz** [comment] 2022-09-17 18:48
Hi all, 
  Turns out the plugin supported this all along: Example:
https://github.com/elycruz/rollup-plugin-sass/blob/f4b2e6457ed52fb2b4ade58c9853ebf124396980/test/index.test.ts#L290-315

Closing issue as is duplicate of #72 .

**Closed as completed by elycruz** 2022-09-17 18:48 UTC

**Comment by elycruz** [comment] 2022-09-17 18:54
Correct example reference:
https://github.com/elycruz/rollup-plugin-sass/blob/f4b2e6457ed52fb2b4ade58c9853ebf124396980/test/index.test.ts#L290-L315
